module.exports = async ctx => {
  const { page, frame, shot, wait } = ctx; const L = require('./lib.cjs')(ctx); const out = ctx.out = {};
  const w = page.viewportSize().width;
  out.host = await page.evaluate(() => { const r = e => e && e.getBoundingClientRect(); const host = document.querySelector('.cve-workspace-host'); const menu = document.querySelector('#adminmenuwrap'); return { host: [r(host).left, r(host).top, r(host).width, r(host).height].map(Math.round), menuW: menu && getComputedStyle(menu).display !== 'none' ? Math.round(r(menu).width) : 0, bar: !!document.querySelector('#wpadminbar') }; });
  out.toolbar = await frame.evaluate(() => { const t = document.querySelector('.cve-w-toolbar'); const vis = s => { const e = document.querySelector(s); return !!e && getComputedStyle(e).display !== 'none' && e.getBoundingClientRect().height > 0; }; return { overflow: t.scrollWidth > t.clientWidth, w: [t.scrollWidth, t.clientWidth], strong: !!t.querySelector('strong'), nativeHeader: vis('.editor-header, .edit-post-header, .edit-site-header'), sidebar: vis('.interface-interface-skeleton__sidebar'), inserter: vis('.editor-inserter-sidebar, .block-editor-inserter__menu'), listView: vis('.editor-list-view-sidebar'), innerBar: vis('#wpadminbar'), innerMenu: vis('#adminmenuwrap'), hint: !!document.querySelector('.cve-w-hint'), buttons: [...t.querySelectorAll('button, a, select')].map(b => (b.getAttribute('aria-label') || b.textContent || b.tagName).trim().slice(0, 18)) }; });
  await shot('qa-a-open-' + w);
  if (out.toolbar.hint) { await frame.locator('.cve-w-hint button', { hasText: 'Got it' }).click(); await wait(300); out.hintStored = await frame.evaluate(() => localStorage.getItem('clara-ve-workspace-hint')); await page.reload(); await wait(6000); const f2 = await (await page.$('iframe.cve-workspace-frame')).contentFrame(); await f2.waitForFunction(() => document.body.classList.contains('cve-native-collapsed'), null, { timeout: 60000 }); await wait(1500); out.hintAfterReload = await f2.evaluate(() => !!document.querySelector('.cve-w-hint')); }
  return out;
};
